name: Basic CI

# ワークフロー起動条件
on:
  # プルリクエストの作成、更新時に実行
  pull_request:
    types:
      - opened
      - synchronize
  
  # mainブランチへのマージ時に実行
  push:
    branches:
      - main

# ジョブ定義
jobs:
  flutter_test:
    name: Flutter Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    # ソースコードをチェックアウト
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # fvm のバージョンとチャネルを環境変数に設定する
      - name: Check fvm
        uses: kuhnroyal/flutter-fvm-config-action@v1
      # Flutter SDKの設定
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}
          # 次回実行時の為にキャッシュしておく
          cache: true
          cache-key: flutter
          cache-path: ${{ runner.tool_cache }}/flutter
      # flutter pub getの実行
      - name: Install pub dependencies
        run: flutter pub get
      # コードフォーマッターを実行
      - name: Run flutter format
        run: flutter format --set-exit-if-changed .
      # 静的解析を実行
      - name: Run flutter analyze
        run: flutter analyze
      # テストを実行
      - name: Run flutter test
        run: flutter test --machine > test-report.log
        if: always()
      # テストをGithub Actions上に表示
      - name: Report test
        uses: dorny/test-reporter@v1
        # テストの結果が失敗だったとしても表示する為、常に実行する
        if: always()
        with:
          name: Flutter test report
          path: 'test-report.log'
          reporter: flutter-json
          fail-on-error: false
