## --- Generate --- ##

gen_l10n:
	@flutter gen-l10n

flutterfire_configure_dev:
	@flutterfire configure --project=bgm-creator-dev --out=lib/firebase_options_dev.dart --ios-bundle-id=com.example.bgm-creator.dev --android-package-name=com.example.bgm_creator.dev

flutterfire_configure_prod:
	@flutterfire configure --project=bgm-creator-701c7 --out=lib/firebase_options_prod.dart --ios-bundle-id=com.example.bgm-creator.prod --android-package-name=com.example.bgm_creator.prod
