name: 'starter_template' # 後で{{name}}に変える
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  firebase_core: ^1.19.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.4
  freezed_annotation: ^2.0.3
  gap: ^2.0.0
  go_router: ^4.1.0
  nil: ^1.1.1 # Reference: https://zenn.dev/wakanao/articles/078809dce5fa74

dev_dependencies:
  build_runner: ^2.1.11
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.0.4
  pedantic_mono: ^1.19.2


flutter:
  uses-material-design: true
